export interface LiquidLayer {
  colorKey: string;
  hidden?: boolean;
}

export interface BottleState {
  id: string;
  layers: LiquidLayer[];
  capacity: number;
}

export interface CurriculumLevel {
  id: string;
  name: string;
  description: string;
  difficultyTier: "beginner" | "apprentice" | "advanced" | "master" | "grandmaster";
  targetCount: number; // bottle count
  bottles: BottleState[];
}

export const LIQUID_SORT_CURRICULUM_LEVELS: CurriculumLevel[] = [
  {
    id: "level_1",
    name: "Level 1: First Pour",
    description: "Gentle starter puzzle with 2 liquid colors across 3 bottles.",
    difficultyTier: "beginner",
    targetCount: 3,
    bottles: [
      { id: "b1", layers: [{ colorKey: "cyan" }, { colorKey: "cyan" }, { colorKey: "magenta" }], capacity: 3 },
      { id: "b2", layers: [{ colorKey: "magenta" }, { colorKey: "magenta" }, { colorKey: "cyan" }], capacity: 3 },
      { id: "b3", layers: [], capacity: 3 },
    ],
  },
  {
    id: "level_2",
    name: "Level 2: Dual Swap",
    description: "Beginner puzzle for learning empty-bottle double moves.",
    difficultyTier: "beginner",
    targetCount: 3,
    bottles: [
      { id: "b1", layers: [{ colorKey: "gold" }, { colorKey: "cyan" }, { colorKey: "gold" }], capacity: 3 },
      { id: "b2", layers: [{ colorKey: "cyan" }, { colorKey: "gold" }, { colorKey: "cyan" }], capacity: 3 },
      { id: "b3", layers: [], capacity: 3 },
    ],
  },
  {
    id: "level_21",
    name: "Level 3: Two Tubes",
    description: "Two colours and one spare bottle — the gentlest first win.",
    difficultyTier: "beginner",
    targetCount: 3,
    bottles: [
      { id: "b1", layers: [{ colorKey: "cyan" }, { colorKey: "gold" }, { colorKey: "cyan" }], capacity: 3 },
      { id: "b2", layers: [{ colorKey: "cyan" }, { colorKey: "gold" }, { colorKey: "gold" }], capacity: 3 },
      { id: "b3", layers: [], capacity: 3 },
    ],
  },
  {
    id: "level_22",
    name: "Level 4: Triple Tip",
    description: "Three colours in three bottles, with one spare to think in.",
    difficultyTier: "beginner",
    targetCount: 4,
    bottles: [
      { id: "b1", layers: [{ colorKey: "blue" }, { colorKey: "blue" }, { colorKey: "emerald" }], capacity: 3 },
      { id: "b2", layers: [{ colorKey: "blue" }, { colorKey: "emerald" }, { colorKey: "emerald" }], capacity: 3 },
      { id: "b3", layers: [{ colorKey: "magenta" }, { colorKey: "magenta" }, { colorKey: "magenta" }], capacity: 3 },
      { id: "b4", layers: [], capacity: 3 },
    ],
  },
  {
    id: "level_3",
    name: "Level 5: Color Steps",
    description: "A three-color warm-up puzzle with generous space.",
    difficultyTier: "apprentice",
    targetCount: 4,
    bottles: [
      { id: "b1", layers: [{ colorKey: "cyan" }, { colorKey: "magenta" }, { colorKey: "cyan" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "magenta" }, { colorKey: "cyan" }, { colorKey: "magenta" }, { colorKey: "cyan" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "gold" }, { colorKey: "gold" }, { colorKey: "gold" }, { colorKey: "gold" }], capacity: 4 },
      { id: "b4", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_4",
    name: "Level 6: Tiny Vials",
    description: "A compact puzzle requiring multi-step layer transfer.",
    difficultyTier: "apprentice",
    targetCount: 4,
    bottles: [
      { id: "b1", layers: [{ colorKey: "emerald" }, { colorKey: "violet" }, { colorKey: "emerald" }, { colorKey: "violet" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "violet" }, { colorKey: "emerald" }, { colorKey: "violet" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "blue" }, { colorKey: "blue" }, { colorKey: "blue" }, { colorKey: "blue" }], capacity: 4 },
      { id: "b4", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_23",
    name: "Level 7: Steady Pour",
    description: "Three colours across four bottles — plan before you tip.",
    difficultyTier: "apprentice",
    targetCount: 5,
    bottles: [
      { id: "b1", layers: [{ colorKey: "gold" }, { colorKey: "gold" }, { colorKey: "violet" }, { colorKey: "cyan" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "cyan" }, { colorKey: "violet" }, { colorKey: "cyan" }, { colorKey: "gold" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "cyan" }, { colorKey: "violet" }, { colorKey: "violet" }, { colorKey: "gold" }], capacity: 4 },
      { id: "b4", layers: [], capacity: 4 },
      { id: "b5", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_24",
    name: "Level 8: First Fog",
    description: "One hidden layer to meet the mystery bottles gently.",
    difficultyTier: "apprentice",
    targetCount: 5,
    bottles: [
      { id: "b1", layers: [{ colorKey: "emerald", hidden: true }, { colorKey: "blue" }, { colorKey: "emerald" }, { colorKey: "blue" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "emerald" }, { colorKey: "orange" }, { colorKey: "emerald" }, { colorKey: "orange" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "orange" }, { colorKey: "orange" }, { colorKey: "blue" }, { colorKey: "blue" }], capacity: 4 },
      { id: "b4", layers: [], capacity: 4 },
      { id: "b5", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_5",
    name: "Level 9: Potion Practice",
    description: "Four colors across five bottles requiring strategic empty space.",
    difficultyTier: "apprentice",
    targetCount: 5,
    bottles: [
      { id: "b1", layers: [{ colorKey: "cyan" }, { colorKey: "magenta" }, { colorKey: "gold" }, { colorKey: "cyan" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "emerald" }, { colorKey: "cyan" }, { colorKey: "magenta" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "gold" }, { colorKey: "emerald" }, { colorKey: "cyan" }, { colorKey: "gold" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "magenta" }, { colorKey: "gold" }, { colorKey: "emerald" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b5", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_11",
    name: "Level 10: Rainbow Cascade",
    description: "Vibrant four-color cascade across 6 tubes for mid-tier warm-up.",
    difficultyTier: "apprentice",
    targetCount: 6,
    bottles: [
      { id: "b1", layers: [{ colorKey: "cyan" }, { colorKey: "gold" }, { colorKey: "magenta" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "emerald" }, { colorKey: "magenta" }, { colorKey: "cyan" }, { colorKey: "gold" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "gold" }, { colorKey: "cyan" }, { colorKey: "emerald" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "magenta" }, { colorKey: "emerald" }, { colorKey: "gold" }, { colorKey: "cyan" }], capacity: 4 },
      { id: "b5", layers: [], capacity: 4 },
      { id: "b6", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_7",
    name: "Level 11: Starter Shelf",
    description: "Five colors with two spare empty bottles.",
    difficultyTier: "advanced",
    targetCount: 6,
    bottles: [
      { id: "b1", layers: [{ colorKey: "violet" }, { colorKey: "tan" }, { colorKey: "violet" }, { colorKey: "tan" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "orange" }, { colorKey: "blue" }, { colorKey: "orange" }, { colorKey: "blue" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "tan" }, { colorKey: "violet" }, { colorKey: "tan" }, { colorKey: "violet" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "blue" }, { colorKey: "orange" }, { colorKey: "blue" }, { colorKey: "orange" }], capacity: 4 },
      { id: "b5", layers: [], capacity: 4 },
      { id: "b6", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_6",
    name: "Level 12: Foggy Forest (Mystery)",
    description: "Introduces Mystery Fog Layers (❓) hidden under top liquid.",
    difficultyTier: "advanced",
    targetCount: 6,
    bottles: [
      { id: "b1", layers: [{ colorKey: "emerald", hidden: true }, { colorKey: "cyan" }, { colorKey: "magenta" }, { colorKey: "gold" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "gold", hidden: true }, { colorKey: "magenta" }, { colorKey: "cyan" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "magenta" }, { colorKey: "emerald" }, { colorKey: "gold" }, { colorKey: "cyan" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "cyan" }, { colorKey: "gold" }, { colorKey: "emerald" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b5", layers: [], capacity: 4 },
      { id: "b6", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_12",
    name: "Level 13: Dual Mystery Chamber",
    description: "Four colors with hidden mystery bottom layers across 6 tubes.",
    difficultyTier: "advanced",
    targetCount: 6,
    bottles: [
      { id: "b1", layers: [{ colorKey: "cyan", hidden: true }, { colorKey: "magenta" }, { colorKey: "gold" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "emerald", hidden: true }, { colorKey: "cyan" }, { colorKey: "magenta" }, { colorKey: "gold" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "gold", hidden: true }, { colorKey: "emerald" }, { colorKey: "cyan" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "magenta", hidden: true }, { colorKey: "gold" }, { colorKey: "emerald" }, { colorKey: "cyan" }], capacity: 4 },
      { id: "b5", layers: [], capacity: 4 },
      { id: "b6", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_13",
    name: "Level 14: Neon Prism",
    description: "Five neon colors across 7 tubes requiring tactical layer buffering.",
    difficultyTier: "advanced",
    targetCount: 7,
    bottles: [
      { id: "b1", layers: [{ colorKey: "cyan" }, { colorKey: "violet" }, { colorKey: "magenta" }, { colorKey: "gold" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "emerald" }, { colorKey: "cyan" }, { colorKey: "violet" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "gold" }, { colorKey: "emerald" }, { colorKey: "cyan" }, { colorKey: "violet" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "magenta" }, { colorKey: "gold" }, { colorKey: "emerald" }, { colorKey: "cyan" }], capacity: 4 },
      { id: "b5", layers: [{ colorKey: "violet" }, { colorKey: "magenta" }, { colorKey: "gold" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b6", layers: [], capacity: 4 },
      { id: "b7", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_14",
    name: "Level 15: Deep Sea Mystery",
    description: "Five ocean colors with hidden mystery layers across 7 tubes.",
    difficultyTier: "advanced",
    targetCount: 7,
    bottles: [
      { id: "b1", layers: [{ colorKey: "blue", hidden: true }, { colorKey: "cyan" }, { colorKey: "emerald" }, { colorKey: "tan" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "tan", hidden: true }, { colorKey: "violet" }, { colorKey: "blue" }, { colorKey: "cyan" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "emerald", hidden: true }, { colorKey: "tan" }, { colorKey: "violet" }, { colorKey: "blue" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "cyan", hidden: true }, { colorKey: "emerald" }, { colorKey: "tan" }, { colorKey: "violet" }], capacity: 4 },
      { id: "b5", layers: [{ colorKey: "violet", hidden: true }, { colorKey: "blue" }, { colorKey: "cyan" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b6", layers: [], capacity: 4 },
      { id: "b7", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_8",
    name: "Level 16: Bright Batch",
    description: "Six colours across six bottles, with two spares to work in.",
    difficultyTier: "master",
    targetCount: 8,
    bottles: [
      { id: "b1", layers: [{ colorKey: "emerald" }, { colorKey: "emerald" }, { colorKey: "violet" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "violet" }, { colorKey: "violet" }, { colorKey: "blue" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "gold" }, { colorKey: "tan" }, { colorKey: "tan" }, { colorKey: "gold" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "magenta" }, { colorKey: "magenta" }, { colorKey: "tan" }, { colorKey: "gold" }], capacity: 4 },
      { id: "b5", layers: [{ colorKey: "gold" }, { colorKey: "blue" }, { colorKey: "violet" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b6", layers: [{ colorKey: "blue" }, { colorKey: "emerald" }, { colorKey: "blue" }, { colorKey: "tan" }], capacity: 4 },
      { id: "b7", layers: [], capacity: 4 },
      { id: "b8", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_15",
    name: "Level 17: Alchemy Lab",
    description: "Six alchemy colors across 8 tubes testing multi-layer sorting skill.",
    difficultyTier: "master",
    targetCount: 8,
    bottles: [
      { id: "b1", layers: [{ colorKey: "cyan" }, { colorKey: "magenta" }, { colorKey: "gold" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "violet" }, { colorKey: "orange" }, { colorKey: "cyan" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "gold" }, { colorKey: "emerald" }, { colorKey: "violet" }, { colorKey: "orange" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "cyan" }, { colorKey: "magenta" }, { colorKey: "gold" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b5", layers: [{ colorKey: "violet" }, { colorKey: "orange" }, { colorKey: "cyan" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b6", layers: [{ colorKey: "gold" }, { colorKey: "emerald" }, { colorKey: "violet" }, { colorKey: "orange" }], capacity: 4 },
      { id: "b7", layers: [], capacity: 4 },
      { id: "b8", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_9",
    name: "Level 18: Mystery Cavern",
    description: "6 colors with 4 hidden Mystery Fog layers.",
    difficultyTier: "master",
    targetCount: 8,
    bottles: [
      { id: "b1", layers: [{ colorKey: "tan", hidden: true }, { colorKey: "violet" }, { colorKey: "violet" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "blue", hidden: true }, { colorKey: "tan" }, { colorKey: "magenta" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "blue", hidden: true }, { colorKey: "violet" }, { colorKey: "emerald" }, { colorKey: "blue" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "violet", hidden: true }, { colorKey: "gold" }, { colorKey: "emerald" }, { colorKey: "tan" }], capacity: 4 },
      { id: "b5", layers: [{ colorKey: "gold" }, { colorKey: "magenta" }, { colorKey: "gold" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b6", layers: [{ colorKey: "blue" }, { colorKey: "tan" }, { colorKey: "gold" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b7", layers: [], capacity: 4 },
      { id: "b8", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_16",
    name: "Level 19: Shadow Vault",
    description: "Six colors with 6 hidden mystery layers across 8 tubes.",
    difficultyTier: "master",
    targetCount: 8,
    bottles: [
      { id: "b1", layers: [{ colorKey: "cyan", hidden: true }, { colorKey: "magenta" }, { colorKey: "gold" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "violet", hidden: true }, { colorKey: "orange" }, { colorKey: "cyan" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "gold", hidden: true }, { colorKey: "emerald" }, { colorKey: "violet" }, { colorKey: "orange" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "cyan", hidden: true }, { colorKey: "magenta" }, { colorKey: "gold" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b5", layers: [{ colorKey: "violet", hidden: true }, { colorKey: "orange" }, { colorKey: "cyan" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b6", layers: [{ colorKey: "gold", hidden: true }, { colorKey: "emerald" }, { colorKey: "violet" }, { colorKey: "orange" }], capacity: 4 },
      { id: "b7", layers: [], capacity: 4 },
      { id: "b8", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_17",
    name: "Level 20: Crystal Palace",
    description: "Seven sparkling gemstone colors across 9 tubes.",
    difficultyTier: "master",
    targetCount: 9,
    bottles: [
      { id: "b1", layers: [{ colorKey: "cyan" }, { colorKey: "tan" }, { colorKey: "orange" }, { colorKey: "violet" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "magenta" }, { colorKey: "cyan" }, { colorKey: "tan" }, { colorKey: "orange" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "gold" }, { colorKey: "magenta" }, { colorKey: "cyan" }, { colorKey: "tan" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "emerald" }, { colorKey: "gold" }, { colorKey: "magenta" }, { colorKey: "cyan" }], capacity: 4 },
      { id: "b5", layers: [{ colorKey: "violet" }, { colorKey: "emerald" }, { colorKey: "gold" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b6", layers: [{ colorKey: "orange" }, { colorKey: "violet" }, { colorKey: "emerald" }, { colorKey: "gold" }], capacity: 4 },
      { id: "b7", layers: [{ colorKey: "tan" }, { colorKey: "orange" }, { colorKey: "violet" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b8", layers: [], capacity: 4 },
      { id: "b9", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_18",
    name: "Level 21: Phantom Labyrinth",
    description: "Seven colors with mystery fog layers across 9 tubes.",
    difficultyTier: "grandmaster",
    targetCount: 9,
    bottles: [
      { id: "b1", layers: [{ colorKey: "cyan", hidden: true }, { colorKey: "tan" }, { colorKey: "orange" }, { colorKey: "violet" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "magenta", hidden: true }, { colorKey: "cyan" }, { colorKey: "tan" }, { colorKey: "orange" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "gold", hidden: true }, { colorKey: "magenta" }, { colorKey: "cyan" }, { colorKey: "tan" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "emerald", hidden: true }, { colorKey: "gold" }, { colorKey: "magenta" }, { colorKey: "cyan" }], capacity: 4 },
      { id: "b5", layers: [{ colorKey: "violet", hidden: true }, { colorKey: "emerald" }, { colorKey: "gold" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b6", layers: [{ colorKey: "orange", hidden: true }, { colorKey: "violet" }, { colorKey: "emerald" }, { colorKey: "gold" }], capacity: 4 },
      { id: "b7", layers: [{ colorKey: "tan", hidden: true }, { colorKey: "orange" }, { colorKey: "violet" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b8", layers: [], capacity: 4 },
      { id: "b9", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_10",
    name: "Level 22: Grandmaster Vault",
    description: "Full spectrum 8 colors across 10 bottles.",
    difficultyTier: "grandmaster",
    targetCount: 10,
    bottles: [
      { id: "b1", layers: [{ colorKey: "cyan" }, { colorKey: "magenta" }, { colorKey: "gold" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "violet" }, { colorKey: "orange" }, { colorKey: "tan" }, { colorKey: "blue" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "emerald" }, { colorKey: "gold" }, { colorKey: "magenta" }, { colorKey: "cyan" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "blue" }, { colorKey: "tan" }, { colorKey: "orange" }, { colorKey: "violet" }], capacity: 4 },
      { id: "b5", layers: [{ colorKey: "gold" }, { colorKey: "cyan" }, { colorKey: "emerald" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b6", layers: [{ colorKey: "tan" }, { colorKey: "blue" }, { colorKey: "violet" }, { colorKey: "orange" }], capacity: 4 },
      { id: "b7", layers: [{ colorKey: "magenta" }, { colorKey: "emerald" }, { colorKey: "cyan" }, { colorKey: "gold" }], capacity: 4 },
      { id: "b8", layers: [{ colorKey: "orange" }, { colorKey: "violet" }, { colorKey: "blue" }, { colorKey: "tan" }], capacity: 4 },
      { id: "b9", layers: [], capacity: 4 },
      { id: "b10", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_19",
    name: "Level 23: Spectrum Challenge",
    description: "Eight full spectrum colors across 10 tubes for true grandmasters.",
    difficultyTier: "grandmaster",
    targetCount: 10,
    bottles: [
      { id: "b1", layers: [{ colorKey: "cyan" }, { colorKey: "blue" }, { colorKey: "tan" }, { colorKey: "orange" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "magenta" }, { colorKey: "cyan" }, { colorKey: "blue" }, { colorKey: "tan" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "gold" }, { colorKey: "magenta" }, { colorKey: "cyan" }, { colorKey: "blue" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "emerald" }, { colorKey: "gold" }, { colorKey: "magenta" }, { colorKey: "cyan" }], capacity: 4 },
      { id: "b5", layers: [{ colorKey: "violet" }, { colorKey: "emerald" }, { colorKey: "gold" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b6", layers: [{ colorKey: "orange" }, { colorKey: "violet" }, { colorKey: "emerald" }, { colorKey: "gold" }], capacity: 4 },
      { id: "b7", layers: [{ colorKey: "tan" }, { colorKey: "orange" }, { colorKey: "violet" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b8", layers: [{ colorKey: "blue" }, { colorKey: "tan" }, { colorKey: "orange" }, { colorKey: "violet" }], capacity: 4 },
      { id: "b9", layers: [], capacity: 4 },
      { id: "b10", layers: [], capacity: 4 },
    ],
  },
  {
    id: "level_20",
    name: "Level 24: Ultimate Master Apex",
    description: "The ultimate 8-color master puzzle with deep mystery fog layers.",
    difficultyTier: "grandmaster",
    targetCount: 10,
    bottles: [
      { id: "b1", layers: [{ colorKey: "cyan", hidden: true }, { colorKey: "blue", hidden: true }, { colorKey: "tan" }, { colorKey: "orange" }], capacity: 4 },
      { id: "b2", layers: [{ colorKey: "magenta", hidden: true }, { colorKey: "cyan", hidden: true }, { colorKey: "blue" }, { colorKey: "tan" }], capacity: 4 },
      { id: "b3", layers: [{ colorKey: "gold", hidden: true }, { colorKey: "magenta", hidden: true }, { colorKey: "cyan" }, { colorKey: "blue" }], capacity: 4 },
      { id: "b4", layers: [{ colorKey: "emerald", hidden: true }, { colorKey: "gold", hidden: true }, { colorKey: "magenta" }, { colorKey: "cyan" }], capacity: 4 },
      { id: "b5", layers: [{ colorKey: "violet", hidden: true }, { colorKey: "emerald", hidden: true }, { colorKey: "gold" }, { colorKey: "magenta" }], capacity: 4 },
      { id: "b6", layers: [{ colorKey: "orange", hidden: true }, { colorKey: "violet", hidden: true }, { colorKey: "emerald" }, { colorKey: "gold" }], capacity: 4 },
      { id: "b7", layers: [{ colorKey: "tan", hidden: true }, { colorKey: "orange", hidden: true }, { colorKey: "violet" }, { colorKey: "emerald" }], capacity: 4 },
      { id: "b8", layers: [{ colorKey: "blue", hidden: true }, { colorKey: "tan", hidden: true }, { colorKey: "orange" }, { colorKey: "violet" }], capacity: 4 },
      { id: "b9", layers: [], capacity: 4 },
      { id: "b10", layers: [], capacity: 4 },
    ],
  },
];

export function getCurriculumLevel(levelId?: string): CurriculumLevel {
  const found = LIQUID_SORT_CURRICULUM_LEVELS.find((l) => l.id === levelId);
  return found || LIQUID_SORT_CURRICULUM_LEVELS[0];
}

