"""Generate shared/scoring-fixtures.json — the language-neutral parity set.

Authors a set of (events, config, now) cases and stamps the EXPECTED outputs by
running the backend engine. The frontend and backend parity tests both assert
their engine reproduces these expected values, so if the two engines ever
diverge, one side's test fails. Re-run after any intentional engine change:

    .venv/bin/python scripts/gen_scoring_fixtures.py
"""

import copy
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.features.progression.scoring import (  # noqa: E402
    DEFAULT_SCORING_CONFIG, _iso_to_ms, score_skill,
)

NOW_MS = _iso_to_ms("2026-07-30T10:00:00.000Z")
_seq = 0


def attempt(outcome="correct", attempt_number=1, hint=False, time_ms=5000,
            difficulty=None, session="s1", day="2026-07-20"):
    global _seq
    _seq += 1
    e = {
        "eventType": "attempt", "outcome": outcome, "attemptNumber": attempt_number,
        "hintUsedBeforeAttempt": hint, "sessionId": session,
        "occurredAt": f"{day}T10:00:{_seq % 60:02d}.000Z",
        "clientTimestampMs": _iso_to_ms(f"{day}T10:00:00.000Z") + _seq * 1000,
    }
    if time_ms is not None:
        e["timeOnTaskMs"] = time_ms
    if difficulty:
        e["details"] = {"difficulty": difficulty}
    return e


def clean(n, **kw):
    return [attempt(outcome="correct", attempt_number=1, **kw) for _ in range(n)]


def build_cases():
    cases = []

    cases.append({"name": "not_started", "events": []})

    cases.append({"name": "beginner_shaky", "events": [
        attempt(outcome="incorrect", attempt_number=1),
        attempt(outcome="correct", attempt_number=2, hint=True),
        attempt(outcome="incorrect", attempt_number=1),
    ]})

    cases.append({"name": "developing_six_clean", "events": clean(6)})

    cases.append({"name": "failed_review_does_not_postpone", "events": [
        *clean(6, session="s1", day="2026-07-20"),
        attempt(outcome="incorrect", session="s2", day="2026-07-23"),
    ]})

    cases.append({"name": "proficient", "events": [
        *clean(4, session="s1", day="2026-07-20", difficulty="easy"),
        *clean(3, session="s1", day="2026-07-20", difficulty="hard"),
        *clean(5, session="s2", day="2026-07-21", difficulty="medium"),
    ]})

    cases.append({"name": "master", "events": [
        *clean(5, session="s1", day="2026-07-20", difficulty="hard"),
        *clean(5, session="s2", day="2026-07-22", difficulty="hard"),
        *clean(5, session="s3", day="2026-07-24", difficulty="hard"),
    ]})

    cases.append({"name": "no_timing_renormalizes",
                  "events": clean(6, time_ms=None)})

    # Injected config: same events as "master" but require 5 distinct days →
    # demonstrates the config actually changes the outcome, identically in both engines.
    strict = copy.deepcopy(DEFAULT_SCORING_CONFIG)
    strict["gates"]["master"]["minDistinctDays"] = 5
    cases.append({"name": "master_events_strict_config", "config": strict, "events": [
        *clean(5, session="s1", day="2026-07-20", difficulty="hard"),
        *clean(5, session="s2", day="2026-07-22", difficulty="hard"),
        *clean(5, session="s3", day="2026-07-24", difficulty="hard"),
    ]})

    return cases


ASSERTED_FIELDS = [
    "level", "plays", "attempts", "sessions", "distinctDays",
    "hardPlays", "difficultyTagged", "nextLevel", "isDue",
    "lastSuccessfulReviewAt", "lastReviewOutcome", "nextReviewAtMs",
]


def expected_for(case):
    config = case.get("config", DEFAULT_SCORING_CONFIG)
    r = score_skill("stu-1", "skill-1", case["events"], config, NOW_MS)
    out = {k: r[k] for k in ASSERTED_FIELDS}
    out["score6"] = round(r["score"], 6)
    out["recentScore6"] = round(r["recentScore"], 6)
    return out


def main():
    cases = build_cases()
    payload = {
        "nowMs": NOW_MS,
        "note": "Generated by backend/scripts/gen_scoring_fixtures.py. "
                "score6/recentScore6 are the score rounded to 6dp for cross-language compare.",
        "cases": [
            {
                "name": c["name"],
                "events": c["events"],
                **({"config": c["config"]} if "config" in c else {}),
                "expected": expected_for(c),
            }
            for c in cases
        ],
    }
    out_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
        "shared", "scoring-fixtures.json",
    )
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"wrote {out_path}")
    for c in payload["cases"]:
        e = c["expected"]
        print(f"  {c['name']:32} level={e['level']:12} score={e['score6']} "
              f"plays={e['plays']} days={e['distinctDays']} due={e['isDue']}")


if __name__ == "__main__":
    main()
