// Generated by scripts/generate-svg-ids.mjs — do not edit.
// Add artwork by dropping a .svg into a category folder here, then run `npm run svg:ids`.

export const SVG_ASSET_IDS = [
  "apple",
  "badge-bright-spark",
  "badge-first-steps",
  "badge-star-champion",
  "badge-star-collector",
  "badge-three-in-a-row",
  "badge-week-warrior",
  "counting-quest",
  "cube",
  "cylinder",
  "grape",
  "mango",
  "orange",
  "star",
  "sund-flower",
  "ten-frame",
  "triangle",
] as const;

export type SvgAssetId = (typeof SVG_ASSET_IDS)[number];

/** Folder each asset lives in. "uncategorised" means it sits at the top level. */
export const SVG_ASSET_CATEGORIES: Record<string, string> = {
  "apple": "fruits",
  "badge-bright-spark": "badges",
  "badge-first-steps": "badges",
  "badge-star-champion": "badges",
  "badge-star-collector": "badges",
  "badge-three-in-a-row": "badges",
  "badge-week-warrior": "badges",
  "counting-quest": "thumbnail",
  "cube": "shapes",
  "cylinder": "shapes",
  "grape": "fruits",
  "mango": "fruits",
  "orange": "fruits",
  "star": "shapes",
  "sund-flower": "flowers",
  "ten-frame": "manipulatives",
  "triangle": "shapes",
};

export const SVG_CATEGORIES = [
  "badges",
  "flowers",
  "fruits",
  "manipulatives",
  "shapes",
  "thumbnail",
] as const;
